services:
  radarr:
    volumes:
      - /mnt/Media/Movies:/mnt/Media/Movies

  sonarr:
    volumes:
      - /mnt/Media/Videos:/mnt/Media/Videos

  speedtestcli:
    container_name: speedtest-cli
    image: moutten/speedtest-cli

  jellyfin:
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - /mnt/Media/Videos:/data/tvshows
      - /mnt/Media/Movies:/data/movies

  qbittorrent:
    volumes:
      - /mnt/Media/torrent_downloads:/mnt/Media/torrent_downloads
      - /mnt/Media/Videos:/mnt/Media/Videos
      - /mnt/Media/Movies:/mnt/Media/Movies

  qbittorrentvpn:
   environment:
     - STRICT_PORT_FORWARD=no
   volumes:
      - /mnt/Media/torrent_downloads:/mnt/Media/torrent_downloads
      - /mnt/Media/Videos:/mnt/Media/Videos
      - /mnt/Media/Movies:/mnt/Media/Movies

